apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pacman-01
  namespace: pacman-01-argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  sourceNamespaces: 
  - pacman-01-dev-*