simple-app:
  # Default values for pacman.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  deploymentName: simple-app-01-dev
  namespace: app-01-dev-01

  clusterAPI: apps.cluster-r67x5.r67x5.sandbox1577.opentlc.com

  replicaCount: 3

  imageRepositoryName: quay.io/marrober/pacman
  imageRepositoryTag: g3a59
  imageRepositoryPullPolicy: IfNotPresent
  

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  securityContext: {}

  serviceName: simple-app
  serviceType: ClusterIP
  servicePort: 8080
  servicePortName: 8080-tcp
  serviceTargetPort: 8080
  serviceWeight: 100
  routeTermination: edge

  autoscalingEnabled: false
