apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-root-01
  namespace: openshift-gitops
spec:
  destination:
    namespace: helm-argo-proj-1-dev-01-01
    server: https://kubernetes.default.svc
  source:
    path: pacman-01
    repoURL: https://github.com/marrober/helm-deployments.git
    targetRevision: main
  project: helm-argo-proj-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:  
    - Validate=true 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s