apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-6-root
  namespace: openshift-gitops
spec:
  destination:
    namespace: argo-root
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/marrober/helm-deployments.git
    path: app-root/apps/pacman-06/env
    targetRevision: main
    directory: 
      recurse: true
  project: pacman-app-08
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:  
    - Validate=true 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s