apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pacman-app-06-dev-01-mco
  namespace: pacman-app-06-dev-01
  labels:
    policy: pacman-app-06-dev-01-managed-cluster-objects
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: pacman-app-06-dev-01-project
        spec:
          severity: medium
          remediationAction: enforce
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1alpha1
                kind: AppProject
                metadata:
                  name: pacman-app-06
                  namespace: openshift-gitops
                spec:
                  clusterResourceWhitelist:
                  - group: '*'
                    kind: '*'
                  destinations:
                  - namespace: '*'
                    server: '*'
                  sourceRepos:
                  - '*'
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: pacman-app-06-dev-01-mco-placement
  namespace: pacman-app-06-dev-01
spec:
  clusterSets:
  - dev-clusters
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementBinding
metadata: 
  name: pacman-app-06-dev-01-mco-binding
placementRef:
  name: pacman-app-06-dev-01-mco-placement
  kind: Placement
  apiGroup: cluster.open-cluster-management.io/v1beta1
subjects:
- name: pacman-app-06-dev-01-mco
  kind: policy
  apiGroup: policy.open-cluster-management.io/v1