apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-pacman-06-dev-01-managed-cluster-objects
placementRef:
  name: placement-app-1-managed-cluster-objects
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: placement-pacman-06-dev-01-managed-cluster-objects
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-pacman-06-dev-01-managed-cluster-objects
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: vendor, operator: In, values: ["OpenShift"]}