apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pacman-app-06
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  sourceRepos:
  - https://github.com/marrober/helm*

  destinations:
  - server: '*'
    namespace: '*'

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
