apiVersion: v1
kind: Namespace
metadata:
  labels: 
    applicationSetHubNamespace: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    targetClusterSet: "dev-clusters"
    project: pacman-app-03
  name: pacman-app-03-dev-02