apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pacman-app-07
  namespace: openshift-gitops
spec:
  description: Project to show how Argo and Tekton can be used together
  sourceRepos:
  - https://github.com/marrober/helm*

  destinations:
  - server: https://kubernetes.default.svc
    namespace: '*'

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding