apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- rbac.yaml
- deployment.yaml
- service.yaml
- route.yaml

images:
- name: quay.io/marrober/pacman
  newTag: twz5g
