apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-root-01
  namespace: openshift-gitops
spec:
  destination:
    namespace: helm-argo-simple-app-01-dev-01
    server: https://kubernetes.default.svc
  source:
    path: pacman-03
    repoURL: https://github.com/marrober/helm-deployments.git
    targetRevision: main
  project: helm-argo-simple-app-01
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:  
    - Validate=true 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s