apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- argo-project.yaml
- root.yaml
- apps.yaml
- policies/hub-cluster-config/01-gitops-operator/policy-openshift-gitops.yaml