---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: managed-clusterset-bindings
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: managed-clusterset-bindings
        spec:
          severity: medium
          remediationAction: enforce
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta2
                kind: ManagedClusterSetBinding
                metadata:
                  name: dev-clusters
                  namespace: openshift-gitops
                spec:
                  clusterSet: dev-clusters
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta2
                kind: ManagedClusterSetBinding
                metadata:
                  name: prod-clusters
                  namespace: openshift-gitops
                spec:
                  clusterSet: prod-clusters
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-managed-clusterset-bindings
  namespace: rhacm-policies
placementRef:
  name: placement-managed-clusterset-bindings
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: managed-clusterset-bindings
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-managed-clusterset-bindings
  namespace: rhacm-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: ["local-cluster"]}