apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: dev-clusters-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - dev-clusters
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            vendor: OpenShift
---
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters-placement-rule
  namespace: openshift-gitops
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: managed-cluster, operator: In, values: ["yes"]}