apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: openshift-gitops
spec:
  destination:
    namespace: argo-root
    server: https://kubernetes.default.svc
  sources:
  - path: app-root/config
    repoURL: https://github.com/marrober/helm-deployments.git
    targetRevision: main
  - path: app-root/apps
    repoURL: https://github.com/marrober/helm-deployments.git
    targetRevision: main
    directory:
      recurse: true
      include: '*app.yaml'
  project: root
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:  
    - Validate=true 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s
