---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: gitops-cluster
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gitops-cluster
        spec:
          severity: medium
          remediationAction: enforce
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps.open-cluster-management.io/v1beta1
                kind: GitOpsCluster
                metadata:
                  name: argo-acm-clusters-dev-clusters
                  namespace: openshift-gitops
                spec:
                  argoServer:
                    cluster: local-cluster
                    argoNamespace: openshift-gitops
                  placementRef:
                    kind: Placement
                    apiVersion: cluster.open-cluster-management.io/v1beta1
                    name: dev-clusters
                    namespace: openshift-gitops
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps.open-cluster-management.io/v1beta1
                kind: GitOpsCluster
                metadata:
                  name: argo-acm-clusters-prod-clusters
                  namespace: openshift-gitops
                spec:
                  argoServer:
                    cluster: local-cluster
                    argoNamespace: openshift-gitops
                  placementRef:
                    kind: Placement
                    apiVersion: cluster.open-cluster-management.io/v1beta1
                    name: prod-clusters
                    namespace: openshift-gitops
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: gitops-cluster-placement
  namespace: rhacm-policies
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
        - "local-cluster"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata: 
  name: gitops-cluster-binding
  namespace: rhacm-policies
placementRef:
  name: gitops-cluster-placement
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
- name: gitops-cluster
  kind: Policy
  apiGroup: policy.open-cluster-management.io