apiVersion: v1
kind: Namespace
metadata:
  labels: 
    applicationSetHubNamespace: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    targetClusterSet: "dev-clusters"
    projectName: pacnew-app-02
  name: pacnew-app-02-dev-01
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-admin
  namespace: pacnew-app-02-dev-01
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: new-gitops-argocd-application-controller
  namespace: new-gitops