---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: application-set-target-resources
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: application-set-target-resources
        spec:
          severity: medium
          remediationAction: enforce
          object-templates-raw: |   
            {{- range $ns:= (lookup "v1" "Namespace" "" "" "applicationSetHubNamespace=true").items }}            
            - complianceType: musthave 
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: argocd-admin
                  namespace: {{ $ns.metadata.name }}
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
                subjects:
                - kind: ServiceAccount
                  name: openshift-gitops-argocd-application-controller
                  namespace: openshift-gitops
            {{- end }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: application-set-target-resources-bindings
  namespace: rhacm-policies
placementRef:
  name: application-set-target-resources-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: application-set-target-resources
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: application-set-target-resources-placement
  namespace: rhacm-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: NotIn, values: ["true"]}