---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: application-set-namespace-roles
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: application-set-namespace-roles
        spec:
          severity: medium
          remediationAction: enforce
          object-templates-raw: |   
            {{- range $ns:= (lookup "v1" "Namespace" "" "" "applicationSetHubNamespace=true").items }}            
            - complianceType: musthave 
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta2
                kind: ManagedClusterSetBinding
                metadata:
                  name: {{ $ns.metadata.annotations.targetClusterSet }}
                  namespace: {{ $ns.metadata.namespace }}
                spec:
                  clusterSet: dev-clusters
            - complianceType: musthave 
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: argocd-admin
                  namespace: {{ $ns.metadata.namespace }}
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
                subjects:
                - kind: ServiceAccount
                  name: openshift-gitops-argocd-application-controller
                  namespace: openshift-gitops
            - complianceType: musthave 
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: mcsb-{{ $ns.metadata.namespace }}
                  namespace: {{ $ns.metadata.namespace }}
                subjects:
                  - kind: ServiceAccount
                    name: openshift-gitops-argocd-application-controller
                    namespace: openshift-gitops
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: open-cluster-management:managedclusterset:bind:dev-clusters            
            {{- end }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: application-set-namespace-roles-bindings
  namespace: rhacm-policies
placementRef:
  name: application-set-namespace-roles-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: application-set-namespace-roles
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: application-set-namespace-roles-placement
  namespace: rhacm-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: In, values: ["true"]}