---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: application-set-hub-resources
  namespace: rhacm-policies
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: application-set-hub-resources
        spec:
          severity: medium
          remediationAction: enforce
          object-templates-raw: |   
            {{- range $ns:= (lookup "v1" "Namespace" "" "" "applicationSetHubNamespace=true").items }}            
            - complianceType: musthave 
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta2
                kind: ManagedClusterSetBinding
                metadata:
                  name: {{ $ns.metadata.annotations.targetClusterSet }}
                  namespace: {{ $ns.metadata.name }}
                spec:
                  clusterSet: {{ $ns.metadata.annotations.targetClusterSet }}
            - complianceType: musthave 
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: mcsb-{{ $ns.metadata.name }}
                subjects:
                  - kind: ServiceAccount
                    name: openshift-gitops-argocd-application-controller
                    namespace: openshift-gitops
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: open-cluster-management:managedclusterset:bind:dev-clusters  
            - complianceType: musthave 
              objectDefinition:
                apiVersion: argoproj.io/v1alpha1
                kind: AppProject
                metadata:
                  name: {{ $ns.metadata.annotations.projectName }}
                  namespace: openshift-gitops
                spec:
                  sourceRepos:
                  - '*'
                  destinations:
                  - server: '*'
                    namespace: '*'
                  clusterResourceWhitelist:
                  - group: ''
                    kind: Namespace
                  - group: 'rbac.authorization.k8s.io'
                    kind: ClusterRole
                  - group: 'rbac.authorization.k8s.io'
                    kind: ClusterRoleBinding
            {{- end }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: application-set-hub-resources-bindings
  namespace: rhacm-policies
placementRef:
  name: application-set-hub-resources-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: application-set-hub-resources
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: application-set-hub-resources-placement
  namespace: rhacm-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: In, values: ["true"]}