---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: managed-cluster-resources
  namespace: rhacm-policies
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: managed-cluster-resources-1
        spec:
          severity: medium
          remediationAction: enforce
          object-templates-raw: |   
            {{- range $ns:= (lookup "v1" "Namespace" "" "" "argocdManaged=true").items }}    
            - complianceType: musthave 
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: argocd-admin
                  namespace: {{ $ns.metadata.name }}
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
                subjects:
                - kind: ServiceAccount
                  name: openshift-gitops-argocd-application-controller
                  namespace: openshift-gitops
            {{- end }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: managed-cluster-resources-2
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRole
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: managed-cluster-resources-2
                rules:
                  - verbs:
                      - get
                      - list
                      - watch
                      - create
                      - update
                      - patch
                      - delete
                    apiGroups:
                      - '*'
                    resources:
                      - deployment
                      - pod
                      - service
                      - configmap
                      - secret
                      - route
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: managed-cluster-resources-2
                subjects:
                  - kind: ServiceAccount
                    name: openshift-gitops-argocd-application-controller
                    namespace: openshift-gitops
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: managed-cluster-resources-2
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: managed-cluster-resources-bindings
  namespace: rhacm-policies
placementRef:
  name: managed-cluster-resources-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: managed-cluster-resources
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: managed-cluster-resources-placement
  namespace: rhacm-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: NotIn, values: ["true"]}