---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: managed-clusterset-bindings
  namespace: rhacm-policies
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: managed-clusterset-bindings
        spec:
          severity: medium
          remediationAction: enforce
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta2
                kind: ManagedClusterSetBinding
                metadata:
                  name: dev-clusters
                  namespace: openshift-gitops
                spec:
                  clusterSet: dev-clusters
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Placement
                metadata:
                  name: dev-clusters
                  namespace: openshift-gitops
                spec:
                  clusterSets:
                    - dev-clusters
                  predicates:
                    - requiredClusterSelector:
                        labelSelector:
                          matchLabels:
                            vendor: OpenShift
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta2
                kind: ManagedClusterSetBinding
                metadata:
                  name: prod-clusters
                  namespace: openshift-gitops
                spec:
                  clusterSet: prod-clusters
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Placement
                metadata:
                  name: prod-clusters-placement
                  namespace: openshift-gitops
                spec:
                  clusterSets:
                    - prod-clusters
                  predicates:
                    - requiredClusterSelector:
                        labelSelector:
                          matchLabels:
                            vendor: OpenShift
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: gitops-create-managed-clusterset-binding-rhacm-policies
                  namespace: rhacm-policies
                subjects:
                  - kind: ServiceAccount
                    name: openshift-gitops-argocd-application-controller
                    namespace: openshift-gitops
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: open-cluster-management:managedclusterset:bind:dev-clusters
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: argocd-managed-rhacm-policies
                  namespace: rhacm-policies
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
                subjects:
                - kind: ServiceAccount
                  name: openshift-gitops-argocd-application-controller
                  namespace: openshift-gitops
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-managed-clusterset-bindings
  namespace: rhacm-policies
placementRef:
  name: placement-managed-clusterset-bindings
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: managed-clusterset-bindings
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-managed-clusterset-bindings
  namespace: rhacm-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: In, values: ["true"]}