apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-clusters-placement-rule
  namespace: rhacm-policies
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: vendor, operator: In, values: ["OpenShift"]}