apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-app-02-dev-02
  namespace: openshift-gitops
spec:
  project: pacman-app-02
  destination:
    namespace: pacman-app-02-dev-02
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/marrober/helm-deployments.git
    path: app-root/apps/pacman-02/deployment/02-dev
    targetRevision: main
    helm:
      releaseName: pacman-helm-dev
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions: 
      - Validate=true 
      - CreateNamespace=true 
      - PrunePropagationPolicy=foreground 
      - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s 