apiVersion: v1
kind: Namespace
metadata:
  labels: 
    applicationSetHubNamespace: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    targetClusterSet: "dev-clusters"
    projectName: pacman-app-01
  name: pacman-app-01-dev-01
