apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pacman-02
  namespace: pacman-02-argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  sourceNamespaces: 
  - pacman-02-dev-*