pacman:
  # Default values for pacman.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  deploymentName: pacman
  namespace: pacman-01-dev-01

  applicationFramework: nodejs
  applicationFrameworkVersion: 16-ubi8

  clusterAPI: cluster-dlb2n.dlb2n.sandbox1885.opentlc.com

  replicaCount: 3

  imageRepositoryName: quay.io/marrober/pacman
  imageRepositoryTag: g3a59
  imageRepositoryPullPolicy: IfNotPresent
  

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  securityContext: {}

  serviceName: pacman
  serviceType: ClusterIP
  servicePort: 8080
  servicePortName: 8080-tcp
  serviceTargetPort: 8080
  serviceWeight: 100
  routeTermination: edge

  autoscalingEnabled: false