apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management-policies-2
  namespace: new-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: new-argo-root
    server: https://kubernetes.default.svc
  source:
    path: app-root-2/config/management-policies
    repoURL: https://github.com/marrober/helm-deployments.git
    targetRevision: main
  project: root
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:  
    - Validate=true 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s
