apiVersion: v1
kind: Namespace
metadata:
  labels: 
    applicationSetHubNamespace: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    targetClusterSet: "dev-clusters"
    projectName: pacman-app-16
  name: pacman-app-16-dev-02
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-admin
  namespace: pacman-app-16-dev-02
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
