apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-group-01
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argo-root
    server: https://kubernetes.default.svc
  source:
    path: app-root/app-group-01
    repoURL: https://github.com/marrober/helm-deployments.git
    targetRevision: main
    directory: 
      recurse: true
  project: root
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 1m
