apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pacman-app-08
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: openshift-gitops
spec:
  sourceRepos:
  - https://github.com/marrober/helm-deployments.git
  - https://marrober.github.io/helm-charts/

  destinations:
  - server: '*'
    namespace: '*'

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding

  namespaceResourceBlacklist:
  namespaceResourceWhitelist:
  orphanedResources:
    warn: false
  roles:
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-08-root
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: argo-root
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/marrober/helm-deployments.git
    path: app-root/apps/pacman-08/env/01-dev
    targetRevision: main
    helm:
      releaseName: pacman-08-dev-01
      valueFiles:
      - values.yaml
  project: pacman-app-08
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:  
    - Validate=true 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pacman-app-08-project
  namespace: openshift-gitops
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gitops-cluster
          namespace: openshift-gitops
        spec:
          severity: medium
          remediationAction: enforce
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1alpha1
                kind: AppProject
                metadata:
                  name: pacman-app-08
                  namespace: openshift-gitops
                spec:
                  clusterResourceWhitelist:
                  - group: '*'
                    kind: '*'
                  destinations:
                  - namespace: '*'
                    server: '*'
                  sourceRepos:
                  - '*'
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: pacman-app-08-project-placement
  namespace: openshift-gitops
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: managed-cluster, operator: In, values: ["yes"]}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata: 
  name: pacman-app-08-project-binding
  namespace: openshift-gitops
placementRef:
  name: pacman-app-08-project-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: pacman-app-08-project
  kind: Policy
  apiGroup: policy.open-cluster-management.io