apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pacman-app-02
  namespace: openshift-gitops
spec:
  sourceRepos:
  - https://github.com/marrober/helm-deployments.git
  - https://marrober.github.io/helm-charts/

  destinations:
  - server: https://kubernetes.default.svc
    namespace: '*'

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding

  namespaceResourceBlacklist:
  namespaceResourceWhitelist:
  orphanedResources:
    warn: false
  roles:
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-02-root
  namespace: openshift-gitops
spec:
  destination:
    namespace: argo-root
    server: https://kubernetes.default.svc
  source:
    path: app-root/apps/pacman-02
    repoURL: https://github.com/marrober/helm-deployments.git
    targetRevision: main
    directory:
      recurse: true
  project: pacman-app-02
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:  
    - Validate=true 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s
